name: parking_app
description: A parking app built with Flutter.

version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
  intl:
  shared_preferences:
  google_maps_flutter: ^2.0.6
  location:
  geolocator:
  flutter_map:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
